### ISSUE TITLE
Complete documentation/code cleanup for teleport confirm front end

### ISSUE THREAD

**Issue by anahiburga** [neu-cs4530/spring-23-team-514#28]
Task does not involve implementation, just finishing documentation and syncing project with linter.

**Comment by cmac4396** [comment]
Major frontend cleanup commit here: 
https://github.com/neu-cs4530/spring-23-team-514/commit/3dd0c42c6e3d830f1ee32bae64c8c8eee3c9d965https://github.com/neu-cs4530/spring-23-team-514/commit/3dd0c42c6e3d830f1ee32bae64c8c8eee3c9d965
